(defun УДАЛИТЬ-ВСЕ-СВОЙСТВА (target)
  (setf (symbol-plist target) nil))


(setf (get 'Ель 'род) "Хвойные")
(setf (get 'Ель 'Семейство) "Сосновые")
(setf (get 'Ель 'цвет) "Зелёный")

(setf (get 'машина 'цвет) "красный")
(setf (get 'машина 'вес) "большой")
(setf (get 'машина 'марка) "БЕЛАЗ")
(setf (get 'машина 'цена) "5 рублей")

(terpri)
(princ "Никулин - задание 47")
(terpri)
(princ "Тест 1, symbol=Ель, свойста=")
(princ (symbol-plist 'Ель))
(terpri)
(УДАЛИТЬ-ВСЕ-СВОЙСТВА 'Ель)
(princ "Тест 1 после вызова функции, symbol=Ель, свойста=")
(princ (symbol-plist 'Ель))
(terpri)
(princ "Тест 2, symbol=машина, свойста=")
(princ (symbol-plist 'машина))
(terpri)
(УДАЛИТЬ-ВСЕ-СВОЙСТВА 'машина)
(princ "Тест 2 после вызова функции, symbol=машина, свойста=")
(princ (symbol-plist 'машина))
